In [43]:
# Import Dependancies
import pandas as pd
from path import Path
import sklearn as skl
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [44]:
# Load data
file_path = "clean_data.csv"
df2 = pd.read_csv(file_path)
df2.head()

,id,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,metformin,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,1,Caucasian,Female,5,6,25,1,1,41,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Caucasian,Female,15,1,1,7,3,59,0,...,0,0,0,0,0,0,3,1,1,1
2,3,AfricanAmerican,Female,25,1,1,7,2,11,5,...,0,0,2,0,0,0,0,0,1,0
3,4,Caucasian,Male,35,1,1,7,2,44,1,...,0,0,0,0,0,0,3,1,1,0
4,5,Caucasian,Male,45,1,1,7,1,51,0,...,0,0,2,0,0,0,2,1,1,0

In [45]:
df2

,id,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,metformin,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,1,Caucasian,Female,5,6,25,1,1,41,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Caucasian,Female,15,1,1,7,3,59,0,...,0,0,0,0,0,0,3,1,1,1
2,3,AfricanAmerican,Female,25,1,1,7,2,11,5,...,0,0,2,0,0,0,0,0,1,0
3,4,Caucasian,Male,35,1,1,7,2,44,1,...,0,0,0,0,0,0,3,1,1,0
4,5,Caucasian,Male,45,1,1,7,1,51,0,...,0,0,2,0,0,0,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71513,101755,Caucasian,Female,75,1,1,7,9,50,2,...,0,0,0,3,0,0,2,1,1,1
71514,101756,Other,Female,45,1,1,7,14,73,6,...,0,0,2,0,0,0,3,1,1,1
71515,101757,Other,Female,65,1,1,7,2,46,6,...,0,0,0,0,0,0,2,0,1,1
71516,101759,Caucasian,Female,85,1,1,7,5,76,1,...,0,0,0,0,0,0,3,1,1,0
71517,101766,Caucasian,Male,75,1,1,7,6,13,3,...,0,0,0,0,0,0,0,0,0,0

In [46]:
#Encoding the Data
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False)

#Encode Column Race
encode_df = pd.DataFrame(enc.fit_transform(df2.race.values.reshape(-1,1)))

#Rename encoded columns
encode_df.columns = enc.get_feature_names(['race'])


# Merge Dataframes
df2 = df2.merge(encode_df,left_index=True,right_index=True)

#Encoding the Data
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False)

#Encode Column Race
encode_df2 = pd.DataFrame(enc.fit_transform(df2.gender.values.reshape(-1,1)))

#Rename encoded columns
encode_df2.columns = enc.get_feature_names(['race'])

# Merge Dataframes
df2 = df2.merge(encode_df2,left_index=True,right_index=True)

c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [47]:
# Classify X and y Data

y = df2['readmitted']
X = df2.drop(columns = ['race','gender'])
X

,id,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,diabetesMed,readmitted,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,race_Female,race_Male,race_Unknown/Invalid
0,1,5,6,25,1,1,41,0,1,0,...,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,2,15,1,1,7,3,59,0,18,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3,25,1,1,7,2,11,5,13,2,...,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,4,35,1,1,7,2,44,1,16,0,...,1,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,5,45,1,1,7,1,51,0,8,0,...,1,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71513,101755,75,1,1,7,9,50,2,33,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71514,101756,45,1,1,7,14,73,6,26,0,...,1,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71515,101757,65,1,1,7,2,46,6,17,1,...,1,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71516,101759,85,1,1,7,5,76,1,22,0,...,1,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71517,101766,75,1,1,7,6,13,3,3,0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [48]:
# Create testing and training set

X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.7, random_state = 6, stratify = y)

In [49]:
# Create scaler instance
X_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [50]:
# Create the Keras Sequential model
nn_model = tf.keras.models.Sequential()

In [51]:
# Add our first Dense layer, including the input layer
inputs = len(X_train_scaled[0])

nodes_first_layer = 36
nodes_second_layer = 15

# Input Layer
nn_model.add(tf.keras.layers.Dense(units=nodes_first_layer, activation="relu", input_dim=inputs))

# Second Layer
nn_model.add(tf.keras.layers.Dense(units=nodes_second_layer, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units = 1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 36)                1332

 dense_12 (Dense)            (None, 15)                555

 dense_13 (Dense)            (None, 1)                 16

=================================================================
Total params: 1,903
Trainable params: 1,903
Non-trainable params: 0
_________________________________________________________________

In [52]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
1565/1565 [==============================] - 1s 668us/step - loss: -217.4305 - accuracy: 0.8771
Epoch 2/100
1565/1565 [==============================] - 1s 666us/step - loss: -2891.2900 - accuracy: 0.8981
Epoch 3/100
1565/1565 [==============================] - 1s 678us/step - loss: -10265.3916 - accuracy: 0.8977
Epoch 4/100
1565/1565 [==============================] - 1s 718us/step - loss: -23382.7637 - accuracy: 0.8971
Epoch 5/100
1565/1565 [==============================] - 1s 715us/step - loss: -42992.5508 - accuracy: 0.8971
Epoch 6/100
1565/1565 [==============================] - 1s 665us/step - loss: -69989.7734 - accuracy: 0.8956
Epoch 7/100
1565/1565 [==============================] - 1s 651us/step - loss: -105239.7266 - accuracy: 0.8956
Epoch 8/100
1565/1565 [==============================] - 1s 654us/step - loss: -149708.3594 - accuracy: 0.8949
Epoch 9/100
1565/1565 [==============================] - 1s 661us/step - loss: -204960.4844 - accuracy: 0.8949
Epoch 10/100
1565/1565 [==============================] - 1s 680us/step - loss: -271401.8750 - accuracy: 0.8939
Epoch 11/100
1565/1565 [==============================] - 1s 704us/step - loss: -349581.7188 - accuracy: 0.8934
Epoch 12/100
1565/1565 [==============================] - 1s 700us/step - loss: -440433.7188 - accuracy: 0.8929
Epoch 13/100
1565/1565 [==============================] - 1s 692us/step - loss: -545293.8750 - accuracy: 0.8930
Epoch 14/100
1565/1565 [==============================] - 1s 694us/step - loss: -665519.4375 - accuracy: 0.8922
Epoch 15/100
1565/1565 [==============================] - 1s 697us/step - loss: -801222.8125 - accuracy: 0.8914
Epoch 16/100
1565/1565 [==============================] - 1s 676us/step - loss: -954385.7500 - accuracy: 0.8914
Epoch 17/100
1565/1565 [==============================] - 1s 680us/step - loss: -1124068.7500 - accuracy: 0.8908
Epoch 18/100
1565/1565 [==============================] - 1s 668us/step - loss: -1312293.7500 - accuracy: 0.8902
Epoch 19/100
1565/1565 [==============================] - 1s 684us/step - loss: -1519201.3750 - accuracy: 0.8906
Epoch 20/100
1565/1565 [==============================] - 1s 677us/step - loss: -1745305.1250 - accuracy: 0.8892
Epoch 21/100
1565/1565 [==============================] - 1s 690us/step - loss: -1994681.6250 - accuracy: 0.8886
Epoch 22/100
1565/1565 [==============================] - 1s 686us/step - loss: -2264748.2500 - accuracy: 0.8878
Epoch 23/100
1565/1565 [==============================] - 1s 700us/step - loss: -2559545.5000 - accuracy: 0.8873
Epoch 24/100
1565/1565 [==============================] - 1s 735us/step - loss: -2877597.7500 - accuracy: 0.8866
Epoch 25/100
1565/1565 [==============================] - 1s 744us/step - loss: -3219773.2500 - accuracy: 0.8863
Epoch 26/100
1565/1565 [==============================] - 1s 690us/step - loss: -3589277.2500 - accuracy: 0.8860
Epoch 27/100
1565/1565 [==============================] - 1s 715us/step - loss: -3983164.7500 - accuracy: 0.8861
Epoch 28/100
1565/1565 [==============================] - 1s 700us/step - loss: -4400673.0000 - accuracy: 0.8860
Epoch 29/100
1565/1565 [==============================] - 1s 668us/step - loss: -4849231.0000 - accuracy: 0.8856
Epoch 30/100
1565/1565 [==============================] - 1s 668us/step - loss: -5325741.0000 - accuracy: 0.8845
Epoch 31/100
1565/1565 [==============================] - 1s 674us/step - loss: -5828892.0000 - accuracy: 0.8844
Epoch 32/100
1565/1565 [==============================] - 1s 676us/step - loss: -6364657.5000 - accuracy: 0.8842
Epoch 33/100
1565/1565 [==============================] - 1s 693us/step - loss: -6936281.0000 - accuracy: 0.8840
Epoch 34/100
1565/1565 [==============================] - 1s 695us/step - loss: -7536983.5000 - accuracy: 0.8835
Epoch 35/100
1565/1565 [==============================] - 1s 710us/step - loss: -8164418.0000 - accuracy: 0.8827
Epoch 36/100
1565/1565 [==============================] - 1s 706us/step - loss: -8831770.0000 - accuracy: 0.8824
Epoch 37/100
1565/1565 [==============================] - 1s 677us/step - loss: -9531998.0000 - accuracy: 0.8816
Epoch 38/100
1565/1565 [==============================] - 1s 677us/step - loss: -10270437.0000 - accuracy: 0.8818
Epoch 39/100
1565/1565 [==============================] - 1s 680us/step - loss: -11046669.0000 - accuracy: 0.8810
Epoch 40/100
1565/1565 [==============================] - 1s 673us/step - loss: -11860207.0000 - accuracy: 0.8810
Epoch 41/100
1565/1565 [==============================] - 1s 674us/step - loss: -12714690.0000 - accuracy: 0.8806
Epoch 42/100
1565/1565 [==============================] - 1s 672us/step - loss: -13604570.0000 - accuracy: 0.8807
Epoch 43/100
1565/1565 [==============================] - 1s 675us/step - loss: -14532914.0000 - accuracy: 0.8800
Epoch 44/100
1565/1565 [==============================] - 1s 674us/step - loss: -15495745.0000 - accuracy: 0.8804
Epoch 45/100
1565/1565 [==============================] - 1s 674us/step - loss: -16506378.0000 - accuracy: 0.8795
Epoch 46/100
1565/1565 [==============================] - 1s 678us/step - loss: -17556960.0000 - accuracy: 0.8796
Epoch 47/100
1565/1565 [==============================] - 1s 688us/step - loss: -18649436.0000 - accuracy: 0.8788
Epoch 48/100
1565/1565 [==============================] - 1s 678us/step - loss: -19792026.0000 - accuracy: 0.8778
Epoch 49/100
1565/1565 [==============================] - 1s 674us/step - loss: -20979302.0000 - accuracy: 0.8774
Epoch 50/100
1565/1565 [==============================] - 1s 676us/step - loss: -22210882.0000 - accuracy: 0.8768
Epoch 51/100
1565/1565 [==============================] - 1s 678us/step - loss: -23484810.0000 - accuracy: 0.8767
Epoch 52/100
1565/1565 [==============================] - 1s 676us/step - loss: -24809414.0000 - accuracy: 0.8759
Epoch 53/100
1565/1565 [==============================] - 1s 678us/step - loss: -26184128.0000 - accuracy: 0.8754
Epoch 54/100
1565/1565 [==============================] - 1s 673us/step - loss: -27606588.0000 - accuracy: 0.8749
Epoch 55/100
1565/1565 [==============================] - 1s 668us/step - loss: -29077898.0000 - accuracy: 0.8745
Epoch 56/100
1565/1565 [==============================] - 1s 679us/step - loss: -30605576.0000 - accuracy: 0.8736
Epoch 57/100
1565/1565 [==============================] - 1s 666us/step - loss: -32176556.0000 - accuracy: 0.8735
Epoch 58/100
1565/1565 [==============================] - 1s 667us/step - loss: -33798292.0000 - accuracy: 0.8728
Epoch 59/100
1565/1565 [==============================] - 1s 665us/step - loss: -35477112.0000 - accuracy: 0.8726
Epoch 60/100
1565/1565 [==============================] - 1s 668us/step - loss: -37216764.0000 - accuracy: 0.8723
Epoch 61/100
1565/1565 [==============================] - 1s 668us/step - loss: -39009484.0000 - accuracy: 0.8717
Epoch 62/100
1565/1565 [==============================] - 1s 666us/step - loss: -40853176.0000 - accuracy: 0.8712
Epoch 63/100
1565/1565 [==============================] - 1s 679us/step - loss: -42757852.0000 - accuracy: 0.8714
Epoch 64/100
1565/1565 [==============================] - 1s 688us/step - loss: -44716064.0000 - accuracy: 0.8711
Epoch 65/100
1565/1565 [==============================] - 1s 681us/step - loss: -46733600.0000 - accuracy: 0.8704
Epoch 66/100
1565/1565 [==============================] - 1s 667us/step - loss: -48811516.0000 - accuracy: 0.8706
Epoch 67/100
1565/1565 [==============================] - 1s 668us/step - loss: -50950908.0000 - accuracy: 0.8704
Epoch 68/100
1565/1565 [==============================] - 1s 668us/step - loss: -53140552.0000 - accuracy: 0.8700
Epoch 69/100
1565/1565 [==============================] - 1s 665us/step - loss: -55406068.0000 - accuracy: 0.8699
Epoch 70/100
1565/1565 [==============================] - 1s 666us/step - loss: -57735768.0000 - accuracy: 0.8694
Epoch 71/100
1565/1565 [==============================] - 1s 677us/step - loss: -60113564.0000 - accuracy: 0.8690
Epoch 72/100
1565/1565 [==============================] - 1s 699us/step - loss: -62569240.0000 - accuracy: 0.8687
Epoch 73/100
1565/1565 [==============================] - 1s 684us/step - loss: -65089560.0000 - accuracy: 0.8683
Epoch 74/100
1565/1565 [==============================] - 1s 673us/step - loss: -67681704.0000 - accuracy: 0.8676
Epoch 75/100
1565/1565 [==============================] - 1s 670us/step - loss: -70327720.0000 - accuracy: 0.8672
Epoch 76/100
1565/1565 [==============================] - 1s 712us/step - loss: -73037368.0000 - accuracy: 0.8669
Epoch 77/100
1565/1565 [==============================] - 1s 689us/step - loss: -75816064.0000 - accuracy: 0.8660
Epoch 78/100
1565/1565 [==============================] - 1s 678us/step - loss: -78669720.0000 - accuracy: 0.8660
Epoch 79/100
1565/1565 [==============================] - 1s 682us/step - loss: -81571584.0000 - accuracy: 0.8656
Epoch 80/100
1565/1565 [==============================] - 1s 673us/step - loss: -84553960.0000 - accuracy: 0.8651
Epoch 81/100
1565/1565 [==============================] - 1s 677us/step - loss: -87632080.0000 - accuracy: 0.8646
Epoch 82/100
1565/1565 [==============================] - 1s 688us/step - loss: -90777272.0000 - accuracy: 0.8642
Epoch 83/100
1565/1565 [==============================] - 1s 677us/step - loss: -93987424.0000 - accuracy: 0.8640
Epoch 84/100
1565/1565 [==============================] - 1s 676us/step - loss: -97299856.0000 - accuracy: 0.8629
Epoch 85/100
1565/1565 [==============================] - 1s 676us/step - loss: -100699648.0000 - accuracy: 0.8627
Epoch 86/100
1565/1565 [==============================] - 1s 674us/step - loss: -104156376.0000 - accuracy: 0.8626
Epoch 87/100
1565/1565 [==============================] - 1s 673us/step - loss: -107680096.0000 - accuracy: 0.8623
Epoch 88/100
1565/1565 [==============================] - 1s 676us/step - loss: -111303680.0000 - accuracy: 0.8620
Epoch 89/100
1565/1565 [==============================] - 1s 677us/step - loss: -114997552.0000 - accuracy: 0.8612
Epoch 90/100
1565/1565 [==============================] - 1s 686us/step - loss: -118754312.0000 - accuracy: 0.8610
Epoch 91/100
1565/1565 [==============================] - 1s 678us/step - loss: -122600816.0000 - accuracy: 0.8611
Epoch 92/100
1565/1565 [==============================] - 1s 677us/step - loss: -126499504.0000 - accuracy: 0.8605
Epoch 93/100
1565/1565 [==============================] - 1s 666us/step - loss: -130494280.0000 - accuracy: 0.8603
Epoch 94/100
1565/1565 [==============================] - 1s 669us/step - loss: -134570752.0000 - accuracy: 0.8598
Epoch 95/100
1565/1565 [==============================] - 1s 673us/step - loss: -138731248.0000 - accuracy: 0.8594
Epoch 96/100
1565/1565 [==============================] - 1s 672us/step - loss: -142978320.0000 - accuracy: 0.8597
Epoch 97/100
1565/1565 [==============================] - 1s 670us/step - loss: -147320128.0000 - accuracy: 0.8590
Epoch 98/100
1565/1565 [==============================] - 1s 674us/step - loss: -151756256.0000 - accuracy: 0.8583
Epoch 99/100
1565/1565 [==============================] - 1s 681us/step - loss: -156276912.0000 - accuracy: 0.8584
Epoch 100/100
1565/1565 [==============================] - 1s 672us/step - loss: -160874800.0000 - accuracy: 0.8579

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

671/671 - 0s - loss: -1.6261e+08 - accuracy: 0.8543 - 389ms/epoch - 580us/step
Loss: -162613120.0, Accuracy: 0.8543064594268799