In [1]:
# Import Dependancies
import pandas as pd
from path import Path
import sklearn as skl
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)

In [2]:
# Load data
file_path = "../diabetes-filtered.csv"
df = pd.read_csv(file_path)
df.head()

,id,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,metformin,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted
0,1,Caucasian,Female,5,6,25,1,1,41,0,...,0,0,0,0,0,0,0,0,0,NO
1,2,Caucasian,Female,15,1,1,7,3,59,0,...,0,0,0,0,0,0,3,1,1,>30
2,3,AfricanAmerican,Female,25,1,1,7,2,11,5,...,0,0,2,0,0,0,0,0,1,NO
3,4,Caucasian,Male,35,1,1,7,2,44,1,...,0,0,0,0,0,0,3,1,1,NO
4,5,Caucasian,Male,45,1,1,7,1,51,0,...,0,0,2,0,0,0,2,1,1,NO

In [3]:
#Encode Reamditted Column

df['readmitted']=df['readmitted'].replace('NO', 0)
df['readmitted']=df['readmitted'].replace('>30', 1)
df['readmitted']=df['readmitted'].replace('<30', 2)

In [4]:
#Encoding the Data
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False)

#Encode Column Race
encode_df = pd.DataFrame(enc.fit_transform(df.race.values.reshape(-1,1)))

#Rename encoded columns
encode_df.columns = enc.get_feature_names(['race'])


# Merge Dataframes
df = df.merge(encode_df,left_index=True,right_index=True)

#Encoding the Data
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False)

#Encode Column Race
encode_df2 = pd.DataFrame(enc.fit_transform(df.gender.values.reshape(-1,1)))

#Rename encoded columns
encode_df2.columns = enc.get_feature_names(['gender'])

# Merge Dataframes
df = df.merge(encode_df2,left_index=True,right_index=True)

c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
c:\Users\Rahul\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [5]:
# Classify X and y Data

y = df['readmitted']
X = df.drop(columns = ['race','gender','readmitted','id'])
X

,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,...,change,diabetesMed,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,gender_Female,gender_Male,gender_Unknown/Invalid
0,5,6,25,1,1,41,0,1,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,15,1,1,7,3,59,0,18,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,25,1,1,7,2,11,5,13,2,0,...,0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,35,1,1,7,2,44,1,16,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,45,1,1,7,1,51,0,8,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71513,75,1,1,7,9,50,2,33,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71514,45,1,1,7,14,73,6,26,0,1,...,1,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71515,65,1,1,7,2,46,6,17,1,1,...,0,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71516,85,1,1,7,5,76,1,22,0,1,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71517,75,1,1,7,6,13,3,3,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [6]:
# Create testing and training set

X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.8, random_state = 6, stratify = y)
X

,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,...,change,diabetesMed,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,gender_Female,gender_Male,gender_Unknown/Invalid
0,5,6,25,1,1,41,0,1,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,15,1,1,7,3,59,0,18,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,25,1,1,7,2,11,5,13,2,0,...,0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,35,1,1,7,2,44,1,16,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,45,1,1,7,1,51,0,8,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71513,75,1,1,7,9,50,2,33,0,0,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71514,45,1,1,7,14,73,6,26,0,1,...,1,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71515,65,1,1,7,2,46,6,17,1,1,...,0,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
71516,85,1,1,7,5,76,1,22,0,1,...,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71517,75,1,1,7,6,13,3,3,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [7]:
# Create scaler instance
X_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Create the Keras Sequential model
nn_model = tf.keras.models.Sequential()

In [9]:
# Add our first Dense layer, including the input layer
inputs = len(X_train_scaled[0])

nodes_first_layer = 30
nodes_second_layer = 15

# Input Layer
nn_model.add(tf.keras.layers.Dense(units=nodes_first_layer, activation="relu", input_dim=inputs))

# Second Layer
nn_model.add(tf.keras.layers.Dense(units=nodes_second_layer, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units = 1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 30)                1050

 dense_1 (Dense)             (None, 15)                465

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 1,531
Trainable params: 1,531
Non-trainable params: 0
_________________________________________________________________

In [10]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [11]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
1788/1788 [==============================] - 2s 680us/step - loss: 0.6589 - accuracy: 0.5410
Epoch 2/100
1788/1788 [==============================] - 1s 670us/step - loss: 0.6439 - accuracy: 0.5531
Epoch 3/100
1788/1788 [==============================] - 1s 714us/step - loss: 0.6394 - accuracy: 0.5557
Epoch 4/100
1788/1788 [==============================] - 1s 681us/step - loss: 0.6348 - accuracy: 0.5586
Epoch 5/100
1788/1788 [==============================] - 1s 683us/step - loss: 0.6313 - accuracy: 0.5599
Epoch 6/100
1788/1788 [==============================] - 1s 671us/step - loss: 0.6279 - accuracy: 0.5594
Epoch 7/100
1788/1788 [==============================] - 1s 664us/step - loss: 0.6235 - accuracy: 0.5630
Epoch 8/100
1788/1788 [==============================] - 1s 673us/step - loss: 0.6166 - accuracy: 0.5625
Epoch 9/100
1788/1788 [==============================] - 1s 712us/step - loss: 0.6115 - accuracy: 0.5624
Epoch 10/100
1788/1788 [==============================] - 1s 718us/step - loss: 0.6021 - accuracy: 0.5637
Epoch 11/100
1788/1788 [==============================] - 1s 742us/step - loss: 0.5905 - accuracy: 0.5635
Epoch 12/100
1788/1788 [==============================] - 1s 686us/step - loss: 0.5730 - accuracy: 0.5635
Epoch 13/100
1788/1788 [==============================] - 1s 666us/step - loss: 0.5523 - accuracy: 0.5618
Epoch 14/100
1788/1788 [==============================] - 1s 668us/step - loss: 0.5227 - accuracy: 0.5620
Epoch 15/100
1788/1788 [==============================] - 1s 675us/step - loss: 0.4840 - accuracy: 0.5621
Epoch 16/100
1788/1788 [==============================] - 1s 668us/step - loss: 0.4385 - accuracy: 0.5620
Epoch 17/100
1788/1788 [==============================] - 1s 722us/step - loss: 0.3719 - accuracy: 0.5621
Epoch 18/100
1788/1788 [==============================] - 1s 676us/step - loss: 0.2857 - accuracy: 0.5617
Epoch 19/100
1788/1788 [==============================] - 1s 673us/step - loss: 0.1850 - accuracy: 0.5618
Epoch 20/100
1788/1788 [==============================] - 1s 676us/step - loss: 0.0582 - accuracy: 0.5627
Epoch 21/100
1788/1788 [==============================] - 1s 668us/step - loss: -0.1069 - accuracy: 0.5620
Epoch 22/100
1788/1788 [==============================] - 1s 676us/step - loss: -0.2732 - accuracy: 0.5594
Epoch 23/100
1788/1788 [==============================] - 1s 672us/step - loss: -0.5069 - accuracy: 0.5590
Epoch 24/100
1788/1788 [==============================] - 1s 686us/step - loss: -0.7631 - accuracy: 0.5598
Epoch 25/100
1788/1788 [==============================] - 1s 690us/step - loss: -1.0435 - accuracy: 0.5557
Epoch 26/100
1788/1788 [==============================] - 1s 671us/step - loss: -1.3905 - accuracy: 0.5540
Epoch 27/100
1788/1788 [==============================] - 1s 673us/step - loss: -1.7631 - accuracy: 0.5558
Epoch 28/100
1788/1788 [==============================] - 1s 670us/step - loss: -2.2216 - accuracy: 0.5536
Epoch 29/100
1788/1788 [==============================] - 1s 671us/step - loss: -2.7008 - accuracy: 0.5545
Epoch 30/100
1788/1788 [==============================] - 1s 670us/step - loss: -3.2773 - accuracy: 0.5549
Epoch 31/100
1788/1788 [==============================] - 1s 669us/step - loss: -3.9452 - accuracy: 0.5564
Epoch 32/100
1788/1788 [==============================] - 1s 668us/step - loss: -4.6794 - accuracy: 0.5581
Epoch 33/100
1788/1788 [==============================] - 1s 679us/step - loss: -5.4845 - accuracy: 0.5547
Epoch 34/100
1788/1788 [==============================] - 1s 670us/step - loss: -6.4114 - accuracy: 0.5568
Epoch 35/100
1788/1788 [==============================] - 1s 670us/step - loss: -7.4883 - accuracy: 0.5558
Epoch 36/100
1788/1788 [==============================] - 1s 670us/step - loss: -8.5664 - accuracy: 0.5551
Epoch 37/100
1788/1788 [==============================] - 1s 677us/step - loss: -9.8783 - accuracy: 0.5553
Epoch 38/100
1788/1788 [==============================] - 1s 681us/step - loss: -11.2505 - accuracy: 0.5544
Epoch 39/100
1788/1788 [==============================] - 1s 677us/step - loss: -12.6882 - accuracy: 0.5547
Epoch 40/100
1788/1788 [==============================] - 1s 672us/step - loss: -14.3385 - accuracy: 0.5549
Epoch 41/100
1788/1788 [==============================] - 1s 685us/step - loss: -16.0816 - accuracy: 0.5536
Epoch 42/100
1788/1788 [==============================] - 1s 670us/step - loss: -18.0205 - accuracy: 0.5564
Epoch 43/100
1788/1788 [==============================] - 1s 673us/step - loss: -20.1699 - accuracy: 0.5562
Epoch 44/100
1788/1788 [==============================] - 1s 773us/step - loss: -22.3574 - accuracy: 0.5541
Epoch 45/100
1788/1788 [==============================] - 1s 764us/step - loss: -24.8792 - accuracy: 0.5537
Epoch 46/100
1788/1788 [==============================] - 1s 764us/step - loss: -27.2510 - accuracy: 0.5557
Epoch 47/100
1788/1788 [==============================] - 1s 752us/step - loss: -30.0651 - accuracy: 0.5537
Epoch 48/100
1788/1788 [==============================] - 1s 765us/step - loss: -32.9764 - accuracy: 0.5545
Epoch 49/100
1788/1788 [==============================] - 1s 751us/step - loss: -36.1774 - accuracy: 0.5547
Epoch 50/100
1788/1788 [==============================] - 1s 797us/step - loss: -39.4057 - accuracy: 0.5555
Epoch 51/100
1788/1788 [==============================] - 1s 751us/step - loss: -43.0197 - accuracy: 0.5523
Epoch 52/100
1788/1788 [==============================] - 1s 751us/step - loss: -46.8104 - accuracy: 0.5527
Epoch 53/100
1788/1788 [==============================] - 1s 745us/step - loss: -50.8681 - accuracy: 0.5539
Epoch 54/100
1788/1788 [==============================] - 1s 779us/step - loss: -54.7407 - accuracy: 0.5552
Epoch 55/100
1788/1788 [==============================] - 1s 829us/step - loss: -59.0603 - accuracy: 0.5531
Epoch 56/100
1788/1788 [==============================] - 1s 752us/step - loss: -63.6192 - accuracy: 0.5531
Epoch 57/100
1788/1788 [==============================] - 1s 753us/step - loss: -68.4351 - accuracy: 0.5536
Epoch 58/100
1788/1788 [==============================] - 1s 752us/step - loss: -73.4798 - accuracy: 0.5543
Epoch 59/100
1788/1788 [==============================] - 1s 748us/step - loss: -78.8209 - accuracy: 0.5535
Epoch 60/100
1788/1788 [==============================] - 1s 756us/step - loss: -84.1478 - accuracy: 0.5527
Epoch 61/100
1788/1788 [==============================] - 1s 748us/step - loss: -89.2364 - accuracy: 0.5548
Epoch 62/100
1788/1788 [==============================] - 1s 746us/step - loss: -96.0245 - accuracy: 0.5543
Epoch 63/100
1788/1788 [==============================] - 1s 763us/step - loss: -102.1856 - accuracy: 0.5536
Epoch 64/100
1788/1788 [==============================] - 1s 767us/step - loss: -108.7901 - accuracy: 0.5532
Epoch 65/100
1788/1788 [==============================] - 1s 806us/step - loss: -115.9236 - accuracy: 0.5541
Epoch 66/100
1788/1788 [==============================] - 1s 756us/step - loss: -123.0216 - accuracy: 0.5522
Epoch 67/100
1788/1788 [==============================] - 1s 808us/step - loss: -130.5704 - accuracy: 0.5535
Epoch 68/100
1788/1788 [==============================] - 1s 758us/step - loss: -138.6350 - accuracy: 0.5514
Epoch 69/100
1788/1788 [==============================] - 1s 754us/step - loss: -146.5281 - accuracy: 0.5541
Epoch 70/100
1788/1788 [==============================] - 1s 760us/step - loss: -155.4464 - accuracy: 0.5519
Epoch 71/100
1788/1788 [==============================] - 1s 755us/step - loss: -163.9632 - accuracy: 0.5552
Epoch 72/100
1788/1788 [==============================] - 1s 754us/step - loss: -173.1477 - accuracy: 0.5503
Epoch 73/100
1788/1788 [==============================] - 1s 752us/step - loss: -182.6511 - accuracy: 0.5523
Epoch 74/100
1788/1788 [==============================] - 1s 747us/step - loss: -192.7578 - accuracy: 0.5537
Epoch 75/100
1788/1788 [==============================] - 1s 748us/step - loss: -201.7987 - accuracy: 0.5501
Epoch 76/100
1788/1788 [==============================] - 1s 755us/step - loss: -213.7557 - accuracy: 0.5486
Epoch 77/100
1788/1788 [==============================] - 1s 759us/step - loss: -224.2315 - accuracy: 0.5477
Epoch 78/100
1788/1788 [==============================] - 1s 806us/step - loss: -235.9864 - accuracy: 0.5482
Epoch 79/100
1788/1788 [==============================] - 1s 813us/step - loss: -248.0522 - accuracy: 0.5467
Epoch 80/100
1788/1788 [==============================] - 1s 798us/step - loss: -260.3754 - accuracy: 0.5462
Epoch 81/100
1788/1788 [==============================] - 1s 783us/step - loss: -273.8427 - accuracy: 0.5460
Epoch 82/100
1788/1788 [==============================] - 1s 759us/step - loss: -286.4494 - accuracy: 0.5471
Epoch 83/100
1788/1788 [==============================] - 1s 801us/step - loss: -300.5234 - accuracy: 0.5471
Epoch 84/100
1788/1788 [==============================] - 1s 785us/step - loss: -314.3693 - accuracy: 0.5468
Epoch 85/100
1788/1788 [==============================] - 1s 765us/step - loss: -329.3166 - accuracy: 0.5464
Epoch 86/100
1788/1788 [==============================] - 1s 756us/step - loss: -345.0525 - accuracy: 0.5470
Epoch 87/100
1788/1788 [==============================] - 1s 772us/step - loss: -359.7147 - accuracy: 0.5472
Epoch 88/100
1788/1788 [==============================] - 1s 751us/step - loss: -375.5655 - accuracy: 0.5455
Epoch 89/100
1788/1788 [==============================] - 1s 750us/step - loss: -392.5224 - accuracy: 0.5481
Epoch 90/100
1788/1788 [==============================] - 1s 751us/step - loss: -407.8997 - accuracy: 0.5479
Epoch 91/100
1788/1788 [==============================] - 1s 760us/step - loss: -425.9637 - accuracy: 0.5465
Epoch 92/100
1788/1788 [==============================] - 1s 753us/step - loss: -444.2432 - accuracy: 0.5477
Epoch 93/100
1788/1788 [==============================] - 1s 818us/step - loss: -462.9656 - accuracy: 0.5454
Epoch 94/100
1788/1788 [==============================] - 1s 799us/step - loss: -482.7478 - accuracy: 0.5476
Epoch 95/100
1788/1788 [==============================] - 1s 784us/step - loss: -502.1958 - accuracy: 0.5461
Epoch 96/100
1788/1788 [==============================] - 1s 756us/step - loss: -521.8795 - accuracy: 0.5473
Epoch 97/100
1788/1788 [==============================] - 1s 760us/step - loss: -542.4698 - accuracy: 0.5474
Epoch 98/100
1788/1788 [==============================] - 1s 752us/step - loss: -565.0532 - accuracy: 0.5478
Epoch 99/100
1788/1788 [==============================] - 1s 764us/step - loss: -586.9786 - accuracy: 0.5465
Epoch 100/100
1788/1788 [==============================] - 1s 774us/step - loss: -609.0629 - accuracy: 0.5478

In [12]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

447/447 - 0s - loss: 60.4710 - accuracy: 0.5452 - 326ms/epoch - 730us/step
Loss: 60.47100830078125, Accuracy: 0.5451622009277344